# Linear Algebra for CpE
## Laboratory 4 : Vector Operations

Now that you have a fundamental knowledge about linear combination, we'll try to apply the fundamental operations

### Objectives
At the end of this activity you will be able to:
1. Referesh knowledge on vector operations while being familiar with new operations such as products.
2. Visualize vector operations.
3. Perform vector operations using Python.

## Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import math

We have dealt with some of the vector operations in the last module, now we will dwell into more operations. In this laboratory, we will tackle addition,multiplication,division and the inner product of a vector.

## Vector Addition

We have encountered vector before especially with your last activity. Vector addition is simply the element-wise addition of the scalar values of the vectors. Let's take the following vectors as a sample:

$$A = \begin{bmatrix}1\\2\\0\end{bmatrix}, B= \begin{bmatrix}3\\1\\-2 \end{bmatrix}$$

So if do a vector addition of these two vectors we'll get:

$$A + B = \begin{bmatrix}4\\3\\-2\end{bmatrix}$$

We can progammatically solve this using `np.add()` or simply using `+`.

In [34]:
A = np.array([1,2,0])
B = np.array([3,1,-2])

In [35]:
A+B

array([ 4,  3, -2])

In [36]:
np.add(A,B)

array([ 4,  3, -2])

## Vector Subtraction

Vector subtraction is similar to your vector addition but you would need to scale the second vector using a negative scalar that is usuall $-1$. So if we subtract vector $B$ from vector $A$ we get:

$$A-B = \begin{bmatrix}-2\\1\\2\end{bmatrix}$$

In Python, this can be achieved by using `np.subtract()` or `-`

In [37]:
np.subtract(A,B)

array([-2,  1,  2])

In [38]:
A-B

array([-2,  1,  2])

## Vector Multiplication

Vector multiplication, like addition does its operations element-wise. So basic vector multiplication can be achieved by multiplying the elements or the scalars of the vectors individually. So:
$$A * B = \begin{bmatrix}3\\2\\0\end{bmatrix}$$
We can implement this in code by using `np.multiply()` or simply operating with `*`.

In [39]:
np.multiply(A,B)

array([3, 2, 0])

In [40]:
A*B

array([3, 2, 0])

## Vector Division

Dividing a vector by another is uncommon, but if the situation specifies that each elements or scalars of the vector would be divided individually we can perform this by:
$$A./B = \begin{bmatrix}\frac{1}{3}\\2\\0\end{bmatrix}$$
Take note that the notation we used here is $./$ for element-wise division, this notation is based in a MATLab notation for element-wise division. This can be achieved in Python using `np.divide()` or `/`.

In [41]:
np.divide(A,B)

array([ 0.33333333,  2.        , -0.        ])

In [42]:
A/B

array([ 0.33333333,  2.        , -0.        ])

## Modulus of a Vector

The modulus of a vector or the magnitude of a vector can be determined using the Pythagorean theorem. Given the vector $A$ and its scalars denoted as $a_n$ where $n$ is the index of the scalar. So if we have:
$$A = \begin{bmatrix}1\\2\end{bmatrix}$$
We can compute the magnitude as:
$$||A|| = \sqrt{a_1^2 + a_2^2} = \sqrt{1^2 + 2^2} = \sqrt{5}$$
So if we have a matrix with more parameters such as:
$$B=\begin{bmatrix}2\\5\\-1\\0\end{bmatrix}$$
We can generalize the Pythagorean theorem to compute for the magnitude as:
$$||B|| = \sqrt{b_1^2 + b_2^2 + b_3^2 + ... +b_n^2} = \sqrt{\sum_{n=1}^{N}b_n^2}$$
And this equation is now called a Euclidian distance or the Euclidean Norm. We can implement this explicitly by for loops or using `np.linalg.norm()` to get the Euclidian Norm.

In [44]:
A = np.array([1,2])
B = np.array([2,5,-1,0])

In [46]:
np.linalg.norm(A)

2.23606797749979

In [48]:
np.linalg.norm(B)

5.477225575051661

## Vector Dot Product / Inner Product

The inner product of a vector is the sum of the products of each elements of the vectors. So given vectors $H$ and $G$ below:
$$H=\begin{bmatrix}1\\3\\6\end{bmatrix}, G = \begin{bmatrix}5\\2\\1\end{bmatrix}$$
We first take the element-wise product of the vectors:
$$H*G = \begin{bmatrix}5\\6\\6\end{bmatrix}$$
Then we take the sum of the products, making it the inner product of a vector:
$$H\cdot G = 17$$
You can solve for the inner product using an explicit function, `np.inner()` or the `@` operator.

In [49]:
H = np.array([1,3,6])
G = np.array([5,2,1])

In [50]:
np.inner(H,G)

17

In [53]:
H @ G

17

## Activity

### Task 1

Make an explicit function (not using any of NumPy's preset functions) solving the modulus of a vector using the Euclidian Norm formula: 
$$||X|| = \sqrt{\sum_{n=1}^{N}x_n^2}$$
Create a program flowchart for your algorithm and explain it in your methodology. Create 6 different vectors which their element count should not be lower than 4 elements. Explain the results at the results discussion section while comparing them to the `np.linalg.norm()` function.

In [35]:
def modulus(vec):
    raisesum = 0
    for element in range(len(vec)):
       
        raisesum = vec[element] **2 + raisesum
        sqr = math.sqrt(raisesum)
    return(sqr)    
    

vect1 = [2, 5, 2, 5, 14]
vect2 = [5, 2, 4, 8, 10]
vect3 = [9, 11, 3, 1, 4]
vect4 = [7, 43, 22, 9, 14]
vect5 = [6, 23, 53, 26, 7]
vect6 = [1, 4, 6, 7, 43]

print("--------------------------------------------------------")
print("Using the function created")
print("--------------------------------------------------------")
print("Vector's magnitude for vect1 = ", modulus(vect1))
print("Vector's magnitude for vect2 = ", modulus(vect2))
print("Vector's magnitude for vect3 = ", modulus(vect3))
print("Vector's magnitude for vect4 = ", modulus(vect4))
print("Vector's magnitude for vect5 = ", modulus(vect5))
print("Vector's magnitude for vect6 = ", modulus(vect6))

#for comparison to np.linalg.form()
print("--------------------------------------------------------")
print("Using np.linalg.norm")
print("--------------------------------------------------------")
print("Vector's magnitude for vect1 = ", np.linalg.norm(vect1))
print("Vector's magnitude for vect2 = ", np.linalg.norm(vect2))
print("Vector's magnitude for vect3 = ", np.linalg.norm(vect3))
print("Vector's magnitude for vect4 = ", np.linalg.norm(vect4))
print("Vector's magnitude for vect5 = ", np.linalg.norm(vect5))
print("Vector's magnitude for vect6 = ", np.linalg.norm(vect6))



--------------------------------------------------------
Using the function created
--------------------------------------------------------
Vector's magnitude for vect1 =  15.937377450509228
Vector's magnitude for vect2 =  14.45683229480096
Vector's magnitude for vect3 =  15.0996688705415
Vector's magnitude for vect4 =  51.56549233741495
Vector's magnitude for vect5 =  64.02343321003646
Vector's magnitude for vect6 =  44.170125650715555
--------------------------------------------------------
Using np.linalg.norm
--------------------------------------------------------
Vector's magnitude for vect1 =  15.937377450509228
Vector's magnitude for vect2 =  14.45683229480096
Vector's magnitude for vect3 =  15.0996688705415
Vector's magnitude for vect4 =  51.56549233741495
Vector's magnitude for vect5 =  64.02343321003646
Vector's magnitude for vect6 =  44.170125650715555


### Task 2

Make an explicit function (not using any of NumPy's preset functions nor the `@` operator) solving the inner product of two vectors using the inner product formula: 
$$A\cdot B = \sum_{n=1}^{N} a_n \times b_n $$
$$whereas: N = len(A) = len(B)$$
Create a program flowchart for your algorithm and explain it in your methodology. Create 5 distinct pairs vectors which their element count should not be lower than 5 elements. Explain the results at the results discussion section while comparing them to the `np.inner()` function.

In [97]:
def inner (vec,vec2):
    dot = 0
    for element in range(len(vec)): 
        dot = vec[element]*vec2[element] + dot
    return (dot)
            
            
vect_1 = [2, 5, 2, 5, 14]
vect_2 = [5, 2, 4, 8, 10]

vect_3 = [44, 11, 4, 1, 16]
vect_4 = [25, 21, 64, 21, 9]

vect_5 = [22, 21, 42, 5, 2]
vect_6 = [43, 21, 63, 22, 4]

vect_7 = [74, 37, 62, 46, 22]
vect_8 = [21, 11, 34, 12, 15]

vect_9 = [32, 46, 22, 52, 11]
vect_10 = [35, 12, 43, 66, 31]

print("--------------------------------------------------------")
print("Using the function created")
print("--------------------------------------------------------")
print("The inner product of first pair is : ", inner(vect_1,vect_2))
print("The inner product of second pair is : ", inner(vect_3,vect_4))
print("The inner product of third pair is : ", inner(vect_5,vect_6))
print("The inner product of fourth pair is : ", inner(vect_7,vect_8))
print("The inner product of fifth pair is : ", inner(vect_9,vect_10))

print("--------------------------------------------------------")
print("For comparison with np.inner()")
print("--------------------------------------------------------")

vect_1 = np.array([2, 5, 2, 5, 14])
vect_2 = np.array([5, 2, 4, 8, 10])

vect_3 = np.array([44, 11, 4, 1, 16])
vect_4 = np.array([25, 21, 64, 21, 9])

vect_5 = np.array([22, 21, 42, 5, 2])
vect_6 = np.array([43, 21, 63, 22, 4])

vect_7 = np.array([74, 37, 62, 46, 22])
vect_8 = np.array([21, 11, 34, 12, 15])

vect_9 = np.array([32, 46, 22, 52, 11])
vect_10 = np.array([35, 12, 43, 66, 31])

print("The inner product of first pair is : ", np.inner(vect_1,vect_2))
print("The inner product of second pair is : ", np.inner(vect_3,vect_4))
print("The inner product of third pair is : ", np.inner(vect_5,vect_6))
print("The inner product of fourth pair is : ", np.inner(vect_7,vect_8))
print("The inner product of fifth pair is : ", np.inner(vect_9,vect_10))


--------------------------------------------------------
Using the function created
--------------------------------------------------------
The inner product of first pair is :  208
The inner product of second pair is :  1752
The inner product of third pair is :  4151
The inner product of fourth pair is :  4951
The inner product of fifth pair is :  6391
--------------------------------------------------------
For comparison with np.inner()
--------------------------------------------------------
The inner product of first pair is :  208
The inner product of second pair is :  1752
The inner product of third pair is :  4151
The inner product of fourth pair is :  4951
The inner product of fifth pair is :  6391


### Task 3

Code the following vector operation and solve them using the given vector values

$$ ((A^2 + B^2) * (A * (B + A*B)./C))*||A + B||$$
$$A = \begin{bmatrix}-0.4\\0.2\\-0.6\end{bmatrix}, B = \begin{bmatrix}-0.2\\0.2\\1\end{bmatrix}, C = \begin{bmatrix}0.2\\-0.1\\-0.5\end{bmatrix}$$

Create a program flowchart for your algorithm and explain it in your methodology. In your results, compare your answer to the expected output, visualize, and explain the resulting vector using a 3D plot.

In [98]:
A = np.array([-0.4,0.2,-0.6])
B = np.array([-0.2,0.2,1])
C = np.array([0.2,-0.1,-0.5])

first = A**2 + B

 

   #* np.linalg.norm(A+B)

Expected answer: <br>
`array([ 0.35377473, -0.70754945,  0.70754945])`

## Conclusion guide

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learn and achieved in this activity. 